# Generated by Django 3.1.7 on 2021-04-26 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210416_0358'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='c_apartment',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='VendorAddress',
            fields=[
                ('v_shop_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('v_shop', models.CharField(max_length=30)),
                ('v_street', models.CharField(max_length=50)),
                ('v_landmark', models.CharField(max_length=30)),
                ('v_city', models.CharField(max_length=20)),
                ('v_state', models.CharField(max_length=20)),
                ('v_country', models.CharField(max_length=20)),
                ('v_pincode', models.CharField(max_length=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.register')),
            ],
        ),
    ]
