# Generated by Django 3.1.7 on 2021-04-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210426_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoraddress',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='VendorAddress',
        ),
    ]
