# Generated by Django 3.1.7 on 2021-04-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_login'),
        ('dashboard', '0003_auto_20210427_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAddress',
            fields=[
                ('v_shop_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('v_shop', models.CharField(max_length=30)),
                ('v_street', models.CharField(max_length=50)),
                ('v_landmark', models.CharField(max_length=30)),
                ('v_city', models.CharField(max_length=20)),
                ('v_state', models.CharField(max_length=20)),
                ('v_country', models.CharField(max_length=20)),
                ('v_pincode', models.CharField(max_length=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.register')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('c_house_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('c_apartment', models.CharField(max_length=30)),
                ('c_street', models.CharField(max_length=50)),
                ('c_landmark', models.CharField(max_length=30)),
                ('c_city', models.CharField(max_length=20)),
                ('c_state', models.CharField(max_length=20)),
                ('c_country', models.CharField(max_length=20)),
                ('c_pincode', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.register')),
            ],
        ),
    ]
