# Generated by Django 3.1.7 on 2021-04-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_customeraddress_vendoraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='c_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='c_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='c_landmark',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='c_pincode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='c_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='customeraddress',
            old_name='c_street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='vendoraddress',
            old_name='v_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='vendoraddress',
            old_name='v_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='vendoraddress',
            old_name='v_landmark',
            new_name='landmark',
        ),
        migrations.RenameField(
            model_name='vendoraddress',
            old_name='v_pincode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='vendoraddress',
            old_name='v_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='vendoraddress',
            old_name='v_street',
            new_name='street',
        ),
    ]
