# Generated by Django 3.1.7 on 2021-05-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_login'),
        ('dashboard', '0005_auto_20210427_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('g_name', models.CharField(max_length=30)),
                ('g_amount', models.IntegerField()),
                ('g_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Canisters',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('c_max_capacity', models.IntegerField()),
                ('c_actual_amount', models.IntegerField()),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.grocery')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.register')),
            ],
        ),
    ]
