# Generated by Django 3.1.7 on 2021-05-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_canisters_grocery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.IntegerField()),
                ('c_name', models.CharField(max_length=30)),
                ('c_max_capacity', models.IntegerField()),
                ('c_actual_amount', models.IntegerField()),
                ('grocery', models.IntegerField()),
                ('register', models.IntegerField()),
            ],
        ),
    ]
