# Generated by Django 3.1.7 on 2021-04-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('l_id', models.IntegerField(auto_created=True)),
                ('l_name', models.CharField(max_length=30)),
                ('l_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('l_password', models.CharField(max_length=30)),
                ('l_role', models.CharField(max_length=10)),
            ],
        ),
    ]
