# Generated by Django 3.1.7 on 2021-04-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='id',
            new_name='sid',
        ),
        migrations.AlterField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='logout_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
