# Generated by Django 3.1.7 on 2021-04-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210427_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('login_time', models.DateTimeField(null=True)),
                ('logout_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
