# Generated by Django 3.1.7 on 2021-05-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210530_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='r_contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
